### ISSUE TITLE
Unable to lead bullet into turn

### ISSUE THREAD

**Issue by laifrank2002** [Clocks-in-a-Cooler/procyon_skies#1]
Because the bullet originates from the center of the ship, when turning and firing the bullet does not exit from the tip of the ship, causing confusion from the player's POV.

Thanks Jimmy!

**Comment by Clocks-in-a-Cooler** [comment]
Will do. I'm currently revamping EVERYTHING, so I might as well do some fixes. Thanks for letting me know about this bug. I'll put this on the list of things to fix.

**Comment by Clocks-in-a-Cooler** [comment]
This _should_ be fixed in the `code-revamp` branch now... haven't tested, though.

I'll close this issue once I get it working.
