### ISSUE TITLE
Health Bar for Asteroids

### ISSUE THREAD

**Issue by laifrank2002** [Clocks-in-a-Cooler/procyon_skies#14]
Adding some sort of healthbar or indication of damage to asteroids.

**Comment by Clocks-in-a-Cooler** [comment]
To clarify...
We're addin a health bar to the asteroid, but only if it's less than full health? (similar to diep.io's approach)

**Comment by laifrank2002** [comment]
I was thinking we did like damage indicators instead (like half damaged vs full health)
