### ISSUE TITLE
Shots similar to smoke trail

### ISSUE THREAD

**Issue by laifrank2002** [Clocks-in-a-Cooler/procyon_skies#3]
"And for two, the shot particles and the particles from the back of the ship are incredibly similar-looking. It's a QOL problem, but it may be a good idea to change them up a bit"

**Comment by Clocks-in-a-Cooler** [comment]
Change them up _how_?

**Comment by laifrank2002** [comment]
Two ways: change bullets or exhaust. Probably easier to do bullets

**Comment by Clocks-in-a-Cooler** [comment]
You can put in a bullet sprite, or you can edit the shape drawn by the camera (`camera.js`, lines 56 through 64). Right now, a blaster bullet is rendered as a thick line.

**Comment by Clocks-in-a-Cooler** [comment]
I've fixed up the smoke bubbles. Instead of simply disappearing, they _should_ fade out now.
(I'm an idiot for messing up an `alpha` variable.)

**Comment by laifrank2002** [comment]
The new diamond things are better, works much better.
